version: 2
jobs:
  py27:
    docker:
      - image: circleci/python:2.7.14-stretch
    environment:
      - TOX_ENV=py27
      - INTEGRATION_TEST_REPO_NAME=github-release-bot/github-release-test-py2
      - INTEGRATION_TEST_GIT_USER_NAME=github-release-bot
      - INTEGRATION_TEST_GIT_USER_EMAIL=github-release-bot@users.noreply.github.com
    steps:
    - checkout
    - run:
        name:
        command: |
          pip install -r requirements-dev.txt
          tox -e ${TOX_ENV}
  py36:
    docker:
      - image: circleci/python:3.6.5-stretch
    environment:
      - TOX_ENV=py36
      - INTEGRATION_TEST_REPO_NAME=github-release-bot/github-release-test-py3
      - INTEGRATION_TEST_GIT_USER_NAME=github-release-bot
      - INTEGRATION_TEST_GIT_USER_EMAIL=github-release-bot@users.noreply.github.com
    steps:
    - checkout
    - run:
        name:
        command: |
          pip install -r requirements-dev.txt
          tox -e ${TOX_ENV}

workflows:
  version: 2
  test-package-publish:
    jobs:
      - py27
      - py36